### ISSUE TITLE
Why doesn't the plugin work?

### ISSUE THREAD

**Issue by kele59** [brzezinskimarcin/vite-plugin-vue-pug-lint#1]
I installed this plugin, but didn't find it to do anything. Is it what it does to format the code or what?

Under what circumstances can the function of this plugin be triggered?

**Comment by brzezinskimarcin** [comment]
This plugin does not format anything, it runs the [pug-lint](https://github.com/pugjs/pug-lint), which checks your templates based on [the rules](https://github.com/pugjs/pug-lint/blob/master/docs/rules.md) you define in the config and reports them in the browser.

In order for the plugin to be triggered, you need to attach the function exported by the plugin to your `vite.config.ts`:
```js
import { fileURLToPath, URL } from 'url'

import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import pugLint from 'vite-plugin-vue-pug-lint';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [pugLint(), vue()],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})
```
By default it takes the config from the `.pug-lintrc` file in the project root. I created an [example repository](https://github.com/brzezinskimarcin/vite-plugin-vue-pug-lint-example) with basic setup.

For instance, in the repository above, there is a rule `disallowClassAttributeWithStaticValue`, which prevents from adding static css classes via attributes (`span(class='example')`) and prefers css literal syntax instead (`span.example`).
With this rule set, the following template:
```pug
<template lang="pug">
.greetings
  h1.green {{ msg }}
  h3
    | You’ve successfully created a project with 
    a(target='_blank', href='https://vitejs.dev/') Vite 
    | + 
    a(target='_blank', href='https://vuejs.org/') Vue 3
    |.
</template>
```
compiles without errors, but the following one (notice the difference in the first line):

```pug
<template lang="pug">
div(class='greetings')
  h1.green {{ msg }}
  h3
    | You’ve successfully created a project with 
    a(target='_blank', href='https://vitejs.dev/') Vite 
    | + 
    a(target='_blank', href='https://vuejs.org/') Vue 3
    |.
</template>
```
results in the compilation error shown in the browser:

![image](https://user-images.githubusercontent.com/33814584/157308752-9a7d7e1b-d4fc-43ef-9a2f-343bf8d6d41d.png)

Hopefully this answers your question.
